---
abstract: 'Load a module specified using Sub::Spec URI'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Spec-Use
requires:
  Log::Any: 0
  Sub::Spec: 1.0.5
  Sub::Spec::URI: 0.10
  Sub::Spec::URI::http: 0.04
  Test::More: 0.96
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Sub-Spec-Use/
  repository: http://github.com/sharyanto/perl-Sub-Spec-Use
version: 0.02
